name: Build PyQt5 App

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:

      - uses: actions/checkout@v4

      - name: Install Python deps
        run: |
          python3 -m pip install -U pip
          pip3 install PyQt5==5.15.4 pyinstaller==5.13.2

      - name: Build
        run: |
          pyinstaller \
            --clean \
            --noconfirm \
            --onefile \
            --windowed \
            main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: dist/*
